Ef 592 modifier le schema electrique pour le stm32
ExoFlex-Inc/Info pull request #56
Opened 2023-07-13 02:53 UTC by Patdup

### Points à valider avant de merge

- [ ] Est-ce que le pull-request est dans une branche connecté sur Jira?
- [ ] Est-ce qu'un test a été fait pour les fonctions ajoutées et ont été testés localement?
- [ ] As-tu update le ReadMe avec les nouveau éléments ajoutées? 
- [ ] As-tu bien commenté ton code?

2023-07-20 00:26 UTC, BigJack325 commented
J'attends le review de @MicahElie avant de check

2023-07-20 22:26 UTC, MicahElie requested changes
Enlever les circuit d'amplification pour les cellules de charge on en aura plus besoin
Enlever les circuit avec les potentio, parce qu'on risque de pas s'en servir

2023-07-25 00:54 UTC, BigJack325 commented
> Enlever les circuit d'amplification pour les cellules de charge on en aura plus besoin Enlever les circuit avec les potentio, parce qu'on risque de pas s'en servir

@Patdup

2023-07-27 00:50 UTC, MicahElie approved these changes

2023-07-27 01:38 UTC, merged